version: '3.7'

networks:
  local_network:
    name: ${NAME}_network

services:
  db:
    container_name: ${NAME}-db
    image: ${MYSQL_IMAGE}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Europe/Budapest"
    volumes:
      - ./config/mysql-custom.cnf:/etc/mysql/conf.d/mysql-custom.cnf
      - ./log/db:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - local_network

  web:
    container_name: ${NAME}-web
    build:
      context: "./"
      dockerfile: web.Dockerfile
      args:
        PHP_IMAGE: ${PHP_IMAGE}
        MYSQL_IMAGE: ${MYSQL_IMAGE}
        PHP_GD_INSTALL: ${PHP_GD_INSTALL}
    depends_on:
      - db
    environment:
      LC_ALL: "hu_HU.UTF-8"
      LANG: "hu_HU.UTF-8"
      LANGUAGE: "hu_HU.UTF-8"
      TZ: "Europe/Budapest"
    volumes:
      - ./site:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./config/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./log/web:/var/log/apache2
    ports:
      - ${PHP_PORT}:80
    networks:
      - local_network
